apiVersion: v1
kind: ConfigMap
metadata:
  name: ragnarok-env
  namespace: card-pro
data:
  .env: |
    APP_NAME=Ragnarok GRPC
    PORT=8080
    DB_CONNECTION=mysql
    DB_HOST=172.18.133.231
    DB_PORT=3306
    DB_USER=root
    DB_PASSWORD=root
    DB_NAME=card_management
    DB_TIMEZONE=Asia/Jakarta
---
apiVersion: v1
kind: Service
metadata:
  name: ragnarok
  namespace: card-pro
  labels:
    run: ragnarok
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ragnarok

  # or using node port
  #apiVersion: v1
  #kind: Service
  #metadata:
  #  name: ragnarok
  #  namespace: card-pro
  #  labels:
  #    run: ragnarok
  #spec:
  #  type: NodePort
  #  selector:
  #    app: ragnarok
  #  ports:
  #    - port: 8080
  #      targetPort: 8080
  #      protocol: TCP
  #      name: http
  #      nodePort: 30080    # Exposed port on the Kubernetes node (must be 30000–32767)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragnarok
  namespace: card-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragnarok
  template:
    metadata:
      labels:
        app: ragnarok
    spec:
      containers:
        - name: ragnarok
          image: npangestu/morges-test-deploy:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ragnarok-env
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: ragnarok-env
          configMap:
            name: ragnarok-env
            defaultMode: 420
      imagePullSecrets:
        - name: regcred
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ragnarok-ingress
  namespace: card-pro
spec:
  ingressClassName: nginx
  rules:
    - host: ragnarok-app.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ragnarok
                port:
                  number: 8080